apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack                                       # Name of ArgoCD application CR
  namespace: argocd                                   # Should be the namespace in which ArgoCD is deployed
spec:
  destination:
    namespace: argocd-apps
    server: https://kubernetes.default.svc  
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 30.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
    - Replace=true
